In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('/home/harsh/Downloads/h.csv')

In [3]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [4]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [12]:
cols=['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated','lat', 'long', 'sqft_living15', 'sqft_lot15']
X=df[cols]
y=df.price

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=70
,random_state=42)

In [14]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
regressor.intercept_

-36813324.24107878

In [17]:
regressor.coef_

array([-3.43210505e+04,  4.20908155e+04,  1.08904215e+02,  1.24137637e-01,
        7.68523575e+02,  5.89111026e+05,  4.94609139e+04,  3.09682934e+04,
        9.72516803e+04,  7.08154962e+01,  3.80887188e+01, -2.46034015e+03,
        2.18089758e+01,  5.60519650e+05, -1.16889735e+05,  2.77858597e+01,
       -3.91341556e-01])

In [18]:
y_pred=regressor.predict(X_test)

In [19]:
pd.DataFrame({'Actual':y_test,'Predicted':y_pred})

          Actual     Predicted
735     365000.0  4.676661e+05
2830    865000.0  7.798139e+05
4106   1038000.0  1.219162e+06
16218  1490000.0  1.647344e+06
19964   711000.0  7.352614e+05
1227    211000.0  2.611154e+05
18849   790000.0  8.066408e+05
19369   680000.0  5.605294e+05
20164   384500.0  3.683965e+05
7139    605000.0  4.817072e+05
2174    638000.0  6.296091e+05
13342   385000.0  5.861151e+05
15468   175000.0  2.934669e+05
7662    365000.0  3.618080e+05
16941   160000.0  2.984150e+05
5304   1070000.0  1.203965e+06
6377    800000.0  2.942351e+05
12319   795127.0  1.135698e+06
18835   355000.0  3.402848e+05
5337    474000.0  5.882793e+05
3018    485000.0  4.145447e+05
1807    930000.0  1.382564e+06
10110   920000.0  7.447342e+05
7609    560000.0  8.872732e+05
20693   654000.0  4.567227e+05
13958   549000.0  5.469032e+05
8918    290000.0  1.263408e+05
18059   275000.0  9.779634e+04
16118   329990.0  3.432580e+05
10366   750000.0  5.819372e+05
...          ...           ...
11275   514000.0  6.035755e+05
9526    282613.0  3.080516e+05
20145   309000.0  3.425766e+05
20924   400000.0  2.411342e+05
15891   310000.0  7.179299e+04
13804   253200.0  1.104621e+05
12909   334009.0  3.983930e+05
10356   500000.0  3.153911e+05
2862    441500.0  4.351737e+05
12369   685000.0  9.343955e+05
13643   327000.0  3.156423e+05
6036    450000.0  3.387508e+05
10069   356000.0  6.702845e+05
7924    525000.0  3.641526e+05
20062   675000.0  3.657100e+05
10815   875000.0  1.281825e+06
5391    345000.0  3.295485e+05
9453    695000.0  8.113804e+05
5371    350000.0  5.371229e+05
10423   695000.0  7.314342e+05
6648    400000.0  5.396899e+05
8350    330000.0  3.113024e+05
9672    265000.0  1.632684e+05
13462   630000.0  7.002194e+05
6051    312000.0  5.003252e+05
4296    156000.0  6.717028e+04
13848   300000.0  3.772204e+05
18722  1225000.0  1.563117e+06
10508   465000.0  4.524623e+05
20126   923990.0  9.293607e+05

[70 rows x 2 columns]

In [20]:
from sklearn import metrics
metrics.mean_absolute_error(y_test,y_pred)

141250.45246328614

In [21]:
metrics.mean_squared_error(y_test,y_pred)

37545316236.50761

In [22]:
np.sqrt(metrics.mean_squared_error(y_test,y_pred))

193766.13800276766